openapi: 3.0.0
info:
  title: Billy Invoicing API
  description: API de facturación de Billy
  version: 0.1.0 Beta
servers:
  - url: 'https://us-central1-invoice-3c998.cloudfunctions.net/v1'
    description: Development
  - url: 'https://us-central1-apollo-preproduction.cloudfunctions.net/v1'
    description: Staging
  - url: 'https://api.billy.com.co/'
    description: Servidor de Billy
paths:
  /invoices:
    $ref: paths/invoices.yaml
  '/invoices/{invoiceId}':
    $ref: 'paths/invoices@{invoiceId}.yaml'
  /payers/institutions:
    $ref: paths/payers@institutions.yaml
  /payers/persons:
    $ref: paths/payers@persons.yaml
  /institutions/findByIdNumber:
    $ref: paths/institutions@findByIdNumber.yaml
  '/institutions/{institutionId}':
    $ref: 'paths/institutions@{institutionId}.yaml'
  /items:
    $ref: paths/items.yaml
  '/items/{itemId}':
    $ref: 'paths/items@{itemId}.yaml'
  /items/types:
    $ref: paths/items@types.yaml
  /items/units:
    $ref: paths/items@units.yaml
  '/users/{userId}':
    $ref: 'paths/users@{userId}.yaml'
  /cities/findByCountryIsoId:
    $ref: paths/cities@findByCountryIsoId.yaml
  '/cities/{cityId}':
    $ref: 'paths/cities@{cityId}.yaml'
  /taxes:
    $ref: paths/taxes.yaml
  /currencies:
    $ref: paths/currencies.yaml
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
